/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belajarMenampilkanGambar;

import java.awt.CardLayout;
import javax.swing.JComboBox;
/**
 *
 * @author asus
 */
public class TampilanGambar extends javax.swing.JFrame {

    /**
     * Creates new form TampilanGambar
     */
    public TampilanGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btnYato = new javax.swing.JButton();
        btnYaboku = new javax.swing.JButton();
        btnHiyori = new javax.swing.JButton();
        btnking = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        meiLB = new javax.swing.JLabel();
        seeleLB = new javax.swing.JLabel();
        kianaLB = new javax.swing.JLabel();
        bronyaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 0));
        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Aplikasi Penampil Gambar atau GIF"));

        btnYato.setText("yato");
        btnYato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatoActionPerformed(evt);
            }
        });
        buttonPanel.add(btnYato);

        btnYaboku.setText("yaboku");
        btnYaboku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYabokuActionPerformed(evt);
            }
        });
        buttonPanel.add(btnYaboku);

        btnHiyori.setText("hiyori");
        btnHiyori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHiyoriActionPerformed(evt);
            }
        });
        buttonPanel.add(btnHiyori);

        btnking.setText("king");
        btnking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkingActionPerformed(evt);
            }
        });
        buttonPanel.add(btnking);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnKeluar);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout(10, 10));

        meiLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/anime-gintama-gintoki-sakata-wallpaper-preview.jpg"))); // NOI18N
        imagePanel.add(meiLB, "yato");

        seeleLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/yato-noragami-bezdomnyi-bog-iato-fon-vektornaia-grafika.jpg"))); // NOI18N
        seeleLB.setToolTipText("");
        imagePanel.add(seeleLB, "yaboku");

        kianaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/thumb-1920-543145.png"))); // NOI18N
        imagePanel.add(kianaLB, "hiyori");

        bronyaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/fthjhmq9b9621.jpg"))); // NOI18N
        bronyaLB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(bronyaLB, "king");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed
    private void btnkianaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "yato");
    }                             
    private void btnYabokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYabokuActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "yaboku");
    }//GEN-LAST:event_btnYabokuActionPerformed

    private void btnHiyoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiyoriActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "hiyori");
    }//GEN-LAST:event_btnHiyoriActionPerformed

    private void btnkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkingActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "king");
    }//GEN-LAST:event_btnkingActionPerformed

    private void btnYatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bronyaLB;
    private javax.swing.JButton btnHiyori;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnYaboku;
    private javax.swing.JButton btnYato;
    private javax.swing.JButton btnking;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel kianaLB;
    private javax.swing.JLabel meiLB;
    private javax.swing.JLabel seeleLB;
    // End of variables declaration//GEN-END:variables
}
